---
- name: Create htpasswd nginx secret file
  no_log: true
  tags:
    - secrets
  kubernetes.core.k8s:
    state: present
    force: true
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: opaque
      metadata:
        name: "{{ nginx_proxy_name }}-htpasswd-{{ suffix }}"
        labels:
          app: "{{ nginx_proxy_name }}"
          env: "{{ env }}"
          suffix: "{{ suffix }}"
      data:
        htpasswd: "{{ lookup('file', nginx_basic_user_file_local_path, rstrip=False) | b64encode }}"
