---

- name: Create Community pipeline cert secret
  no_log: true
  kubernetes.core.k8s:
    state: present
    force: true
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: community-operator-signing-pipeline-certs
        labels:
          app: "{{ community_signing_pipeline_name }}"
          suffix: "{{ suffix }}"
          env: "{{ env }}"
      data:
        community-operator-signing-pipeline.key: "{{ lookup('file', community_signing_pipeline_private_key_local_path, rstrip=False) | b64encode }}"
        community-operator-signing-pipeline.pem: "{{ lookup('file', community_signing_pipeline_private_cert_local_path, rstrip=False) | b64encode }}"

- name: Create signing pub key secret
  no_log: true
  tags:
    - secrets
  kubernetes.core.k8s:
    state: present
    force: true
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: opaque
      metadata:
        name: signing-pub-key
        labels:
          app: operator-pipeline
          suffix: "{{ suffix }}"
          env: "{{ env }}"
      data:
        sig-key.pub: "{{ lookup('file', signing_pub_key_local_path, rstrip=False) | b64encode }}"
