$ANSIBLE_VAULT;1.1;AES256
30646436396365333834333262656261363161616332313033303763366237663430306131383565
3633373266383935343934656233373262396431326531380a376137376638373435373931626133
63633461653663333561396539323032396634313034393237376563656236323863393539376663
3739326362333138320a313530383339303464653137616131343762393735636263343938333761
63393531636434363934323832333765643863616532363838393562646234353666613961663832
62323835356438303134343437313239383538306431373865343130663439613539393664396664
38393265356339383037303562626565303865346431346261386363343061383832393131393061
64346635323138623330333864653533363961336131306531626564616331313563396133346164
64396264323763663031613739616564363265613465313435333134383336653262376238396537
62386166323133313333623365333561333437313164323135633635643737616236393933373834
66613265363835346161386364666138396465363630346565343830653764393532313263353833
39643564323430376639333630363561613832303335646464336462313334653266313530326134
62363563316232663163383365346135663532386136376666333236303163303439
