---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-ci-results-attempt
spec:
  params:
    - name: md5sum
    - name: pyxis_url
    - name: cert_project_id
    - name: operator_version
  results:
    - name: preflight_results_exists
  workspaces:
    - name: results
  steps:
    - name: get-ci-results
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.results.path)
      script: |
        #! /usr/bin/env bash
        # Curl Pyxis results endpoint
        # If results exists, store them in the workspace
        echo true | tee $(results.preflight_results_exists.path)
