---
- name: Create trigger enabling running Release pipeline via GitHub webhook
  tags:
    - webhook-release
  block:
    - name: Create Release pipeline Trigger Binding
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          # To see the PR webhook payload, set the logLevel to debug in configmap config-logging-triggers
          # Other GitHub PR webhook payload example: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: TriggerBinding
          metadata:
            name: operator-release-pipeline-trigger-binding
            labels:
              app: operator-pipeline
              suffix: "{{ suffix }}"
              env: "{{ env }}"
          spec:
            params:
              - name: git_repo_url
                value: $(body.pull_request.base.repo.clone_url)
              - name: git_commit
                value: $(body.pull_request.merge_commit_sha)
              - name: git_pr_title
                value: $(body.pull_request.title)
              - name: git_pr_url
                value: $(body.pull_request.html_url)
              - name: git_base_branch
                value: $(body.pull_request.base.ref)
              - name: env
                value: "{{ env }}"
              - name: pipeline_image
                value: "{{ operator_pipeline_image_pull_spec }}"
              - name: metrics_endpoint
                value: "{{ pipelines_metrics_endpoint }}"
    - name: Create Release pipeline Trigger Template
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: TriggerTemplate
          metadata:
            name: operator-release-pipeline-trigger-template
            labels:
              app: operator-pipeline
              suffix: "{{ suffix }}"
              env: "{{ env }}"
          spec:
            params:
              - name: git_repo_url
              - name: git_commit
              - name: git_pr_title
              - name: git_pr_url
              - name: git_base_branch
              - name: is_latest
              - name: env
              - name: pipeline_image
              - name: metrics_endpoint
            resourcetemplates:
              - apiVersion: tekton.dev/v1beta1
                kind: PipelineRun
                metadata:
                  generateName: operator-release-pipeline-run
                spec:
                  timeout: "1h30m0s"
                  pipelineRef:
                    name: operator-release-pipeline
                  params:
                    - name: git_repo_url
                      value: $(tt.params.git_repo_url)
                    - name: git_commit
                      value: $(tt.params.git_commit)
                    - name: git_pr_title
                      value: $(tt.params.git_pr_title)
                    - name: git_pr_url
                      value: $(tt.params.git_pr_url)
                    - name: git_base_branch
                      value: $(tt.params.git_base_branch)
                    - name: is_latest
                      value: "true"
                    - name: env
                      value: $(tt.params.env)
                    - name: pipeline_image
                      value: $(tt.params.pipeline_image)
                    - name: metrics_endpoint
                      value: $(tt.params.metrics_endpoint)
                  workspaces:
                    - name: repository
                      volumeClaimTemplate:
                        spec:
                          accessModes:
                            - ReadWriteOnce
                          resources:
                            requests:
                              storage: 5Gi
                    - name: results
                      volumeClaimTemplate:
                        spec:
                          accessModes:
                            - ReadWriteOnce
                          resources:
                            requests:
                              storage: 100Mi
                    - name: image-data
                      volumeClaimTemplate:
                        spec:
                          accessModes:
                            - ReadWriteOnce
                          resources:
                            requests:
                              storage: 100Mi
                    - name: registry-credentials
                      secret:
                        secretName: "registry-dockerconfig-secret"
