---
- name: Create trigger enabling running Hosted pipeline via GitHub webhook
  tags:
    - webhook-hosted
  block:
    - name: Create Hosted pipeline Trigger Binding
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          # To see the PR webhook payload, set the logLevel to debug in configmap config-logging-triggers
          # Other GitHub PR webhook payload example: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: TriggerBinding
          metadata:
            name: operator-hosted-pipeline-trigger-binding
            labels:
              app: operator-pipeline
              suffix: "{{ suffix }}"
              env: "{{ env }}"
          spec:
            params:
              - name: git_pr_branch
                value: $(body.pull_request.head.ref)
              - name: git_pr_title
                value: $(body.pull_request.title)
              - name: git_pr_url
                value: $(body.pull_request.html_url)
              - name: git_fork_url
                value: $(body.pull_request.head.repo.html_url)
              - name: git_repo_url
                value: $(body.pull_request.base.repo.html_url)
              - name: git_username
                value: $(body.pull_request.head.user.login)
              - name: git_commit
                value: $(body.pull_request.head.sha)
              - name: pr_head_label
                value: $(body.pull_request.head.label)
              - name: env
                value: "{{ env }}"
              - name: preflight_min_version
                value: "{{ preflight_min_version }}"
              - name: ci_min_version
                value: "{{ ci_min_version }}"

    - name: Create Hosted pipeline Trigger Template
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: TriggerTemplate
          metadata:
            name: operator-hosted-pipeline-trigger-template
            labels:
              app: operator-pipeline
              suffix: "{{ suffix }}"
              env: "{{ env }}"
          spec:
            params:
              - name: git_pr_branch
              - name: git_pr_title
              - name: git_pr_url
              - name: git_fork_url
              - name: git_repo_url
              - name: git_username
              - name: git_commit
              - name: pr_head_label
              - name: env
              - name: preflight_min_version
              - name: ci_min_version
            resourcetemplates:
              - apiVersion: tekton.dev/v1beta1
                kind: PipelineRun
                metadata:
                  generateName: operator-hosted-pipeline-run
                spec:
                  pipelineRef:
                    name: operator-hosted-pipeline
                  params:
                    - name: git_pr_branch
                      value: $(tt.params.git_pr_branch)
                    - name: git_pr_title
                      value: $(tt.params.git_pr_title)
                    - name: git_pr_url
                      value: $(tt.params.git_pr_url)
                    - name: git_fork_url
                      value: $(tt.params.git_fork_url)
                    - name: git_repo_url
                      value: $(tt.params.git_repo_url)
                    - name: git_username
                      value: $(tt.params.git_username)
                    - name: pr_head_label
                      value: $(tt.params.pr_head_label)
                    - name: env
                      value: $(tt.params.env)
                    - name: preflight_min_version
                      value: $(tt.params.preflight_min_version)
                    - name: ci_min_version
                      value: $(tt.params.ci_min_version)
                    - name: git_commit
                      value: $(tt.params.git_commit)
                  workspaces:
                    - name: repository
                      volumeClaimTemplate:
                        spec:
                          accessModes:
                            - ReadWriteOnce
                          resources:
                            requests:
                              storage: 5Gi
                    - name: results
                      volumeClaimTemplate:
                        spec:
                          accessModes:
                            - ReadWriteOnce
                          resources:
                            requests:
                              storage: 100Mi
                    - name: registry-credentials
                      secret:
                        secretName: "registry-dockerconfig-credentials"
                    - name: pyxis-ssl-credentials
                      secret:
                        secretName: "operator-pipeline-api-certs"
                    - name: github-bot-token
                      secret:
                        secretName: "github-bot-token"
                    # TODO: passing kubeconfig here is just a temporary workaround to make the task pass
                    - name: kubeconfig
                      secret:
                        secretName: "kubeconfig"
                    - name: hydra-credentials
                      secret:
                        secretName: "hydra-credentials"
