$ANSIBLE_VAULT;1.1;AES256
34656430343230393430306431366430336163363039336665303265313236393961633837666564
3832643138336630646233663037633137313362323435370a373766333462633636376430366431
33333962316437343962373736366238363662666562663065636331366137656666663339623231
6133333439393232300a333863333964643561636435373065366433613866383530353737626662
34333965653861373938396261336161353266386263313836393638336363626363336262666431
63393337353033623435306231356238363563393066333031666335656632393764363465343535
39313231623238633233353164336365653432636562623931336564303831353961656432393337
34303432633635373362303261343462643437323734353862633034363664386533356438333866
65353164633762663839306566393864623836386335393336646536363939356439306531383534
38386164626136303065643938663863356361366131613164626465396636316432663536373661
39363963343735343132396334636430303065336334343565313062613836363461323832306334
38646334613862653438306362393362366437316263623262343735313265363830643665376536
65303664663061376266363138356339633561343133323135303034396462383433
