---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: index-audit
spec:
  params:
    - name: operator_test_playbook_repo
      description: "Operator test playbook repo"
      type: string
      default: "https://github.com/redhat-openshift-ecosystem/operator-test-playbooks"
    - name: operator_test_playbook_branch
      description: "Operator test playbook branch"
      type: string
      default: "upstream-community"
    - name: gitInitImage
      description: The image providing the git-init binary that the checkout task runs.
      type: string
      default: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2"
    - name: ansible-runner-image
      description: Ansible runner image
      type: string
      default: "quay.io/operator_testing/operator-test-playbooks:dev-tekton"
    - name: indexes
      description: Comma separated list of indexes to audit
      type: string
      default: "quay.io/openshift-community-operators/catalog_tmp:v4.12,quay.io/openshift-community-operators/catalog_tmp:v4.12s"
    - name: kubeconfig_secret_name
      description: The name of the Kubernetes Secret that contains the kubeconfig.
      default: kubeconfig
    - name: kubeconfig_secret_key
      description: The key within the Kubernetes Secret that contains the kubeconfig.
      default: kubeconfig
  workspaces:
    - name: pipeline
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.operator_test_playbook_repo)
        - name: revision
          value: $(params.operator_test_playbook_branch)
        - name: gitInitImage
          value: $(params.gitInitImage)
      workspaces:
        - name: output
          workspace: pipeline

    - name: index-audit-prepare
      runAfter:
        - checkout
      taskSpec:
        params:
          - name: project-dir
            description: The project directory under the workspace runner-dir
            default: 'upstream'
          - name: indexes
            description: Comma separated list of indexes to audit
            type: string
            default: "quay.io/openshift-community-operators/catalog_tmp:v4.12,quay.io/openshift-community-operators/catalog_tmp:v4.12s"

        steps:
          - name: debug
            image: alpine:latest
            script: |
              mkdir -p $(workspaces.runner-dir.path)/$(params.project-dir)/env || true
              echo "--tags index_verify -e run_upstream=true -e run_prepare_catalog_repo_upstream=false -e container_tool=podman -e iv_indexes=$(params.indexes) -e container_run_mode=pod -e kubeconfig_path=/etc/kubeconfig-volume/$(params.kubeconfig_secret_key)" > $(workspaces.runner-dir.path)/$(params.project-dir)/env/cmdline
              echo "ansible_connection: local" > $(workspaces.runner-dir.path)/$(params.project-dir)/env/extravars
            securityContext:
              runAsNonRoot: true
              runAsUser: 65532
              runAsGroup: 65532
        workspaces:
          - name: runner-dir
      workspaces:
        - name: runner-dir
          workspace: pipeline

    - name: index-audit
      taskRef:
        name: ansible-runner
        kind: Task
      runAfter:
        - index-audit-prepare
      params:
        - name: project-dir
          value: upstream
        - name: args
          value: ["-p", "local.yml", "--inventory", "localhost,"]
        - name: image
          value: quay.io/operator_testing/operator-test-playbooks:dev-tekton
      workspaces:
        - name: runner-dir
          workspace: pipeline
