---
- name: Deploy all the operator pipelines
  hosts: all
  vars_files:
    - ../vaults/{{ env }}/secret-vars.yml
    - ../vaults/{{ env }}/ocp-token.yml
  roles:
    - operator-pipeline
    - nginx_proxy
  environment:
    K8S_AUTH_API_KEY: '{{ ocp_token }}'
    K8S_AUTH_HOST: '{{ ocp_host }}'
