---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-bundle-path
spec:
  params:
    - name: ubi8_minimal_image
      description: ubi8 minimal image
      default: "registry.access.redhat.com/ubi8-minimal@sha256:54ef2173bba7384dc7609e8affbae1c36f8a3ec137cacc0866116d65dd4b9afe"
    - name: git_pr_title
  results:
    - name: bundle_path
  steps:
    - name: get-bundle-path
      image: "$(params.ubi8_minimal_image)"
      env:
        - name: PR_TITLE
          value: $(params.git_pr_title)
      script: |
        #! /usr/bin/env bash
        set -xe

        # remove "operator " prefix
        OPERATOR_NAME_AND_VERSION=${PR_TITLE#operator }

        # remove brackets in version, and concatenate name and version with slash
        BUNDLE_PATH=$(echo $OPERATOR_NAME_AND_VERSION | tr -d "()" | tr " " "/")

        BUNDLE_PATH=$(echo operators/$BUNDLE_PATH)

        echo -n $BUNDLE_PATH | tee $(results.bundle_path.path)
