---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inspect-image
spec:
  params:
    - name: skopeo_image
      description: Skopeo image
      default: "registry.redhat.io/rhel8/skopeo:8.4-13"
    - name: podman_image
      description: Podman image
      default: "registry.redhat.io/rhel8/podman:8.4-14"
    - name: image
      description: reference to the existing bundle image
    - name: registry
      description: Registry that contains bundle image
  workspaces:
    - name: registry-credentials
      description: Docker config for retrieving the bundle image
    - name: image-data
      description: Workspace to store the large json files with the image data
  steps:
    - name: skopeo-inspect
      image: "$(params.skopeo_image)"
      script: |
        set -xe

        skopeo login $(params.registry) --authfile $(workspaces.registry-credentials.path)/.dockerconfigjson \

        skopeo inspect docker://$(params.image) > $(workspaces.image-data.path)/skopeo.json
    - name: podman-inspect
      image: "$(params.podman_image)"
      script: |
        set -xe

        podman pull $(params.image)

        podman image inspect $(params.image) > $(workspaces.image-data.path)/podman.json
