---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: reserve-operator-name
spec:
  params:
    - name: pipeline_image
    - name: association
      description: The association that the operator belongs in, usually the isv_pid.
    - name: operator_name
      description: The operator name to be reserved.
    - name: source
      description: The source catalog the operator belongs to, usually "redhat-marketplace" or "certified-operators"
    - name: pyxis_ssl_secret_name
      description: Kubernetes secret name that contains the Pyxis SSL files.
    - name: pyxis_ssl_cert_secret_key
      description: The key within the Kubernetes secret that contains the Pyxis SSL cert.
    - name: pyxis_ssl_key_secret_key
      description: The key within the Kubernetes secret that contains the Pyxis SSL key.
    - name: pyxis_url
      description: Pyxis instance to reserve the operator name on.
      default: https://pyxis.engineering.redhat.com
  volumes:
    - name: pyxis-ssl-volume
      secret:
        secretName: "$(params.pyxis_ssl_secret_name)"
        optional: false
  steps:
    - name: reserve-operator-name
      image: "$(params.pipeline_image)"
      env:
        - name: PYXIS_CERT_PATH
          value: /etc/pyxis-ssl-volume/$(params.pyxis_ssl_cert_secret_key)
        - name: PYXIS_KEY_PATH
          value: /etc/pyxis-ssl-volume/$(params.pyxis_ssl_key_secret_key)
        - name: ASSOCIATION
          value: $(params.association)
        - name: SOURCE
          value: $(params.source)
      volumeMounts:
        - name: pyxis-ssl-volume
          readOnly: true
          mountPath: "/etc/pyxis-ssl-volume"
      script: |
        #! /usr/bin/env bash
        set -xe

        echo "Attempting to reserve operator name for association $ASSOCIATION"

        reserve-operator-name \
          --association $ASSOCIATION \
          --operator-name "$(params.operator_name)" \
          --pyxis-url "$(params.pyxis_url)" \
          --source $SOURCE \
          --verbose
