---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: reserve-operator-name
spec:
  params:
    - name: association
      description: The assocation that the operator belongs in, usually the isv_pid.
    - name: operator_name
      description: The operator name to be reserved.
    - name: pyxis_cert_path
      default: ""
      description: Path to Pyxis certificates. Valid only when internal Pyxis is used.
    - name: pyxis_key_path
      default: ""
      description: Path to Pyxis key. Valid only when internal Pyxis is used.
    - name: pyxis_url
      description: Pyxis instance to reserve the operator name on.
      default: https://pyxis.engineering.redhat.com
  workspaces:
    - name: pyxis-ssl-credentials
      optional: false
  steps:
    - name: reserve-operator-name
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      env:
        - name: PYXIS_CERT_PATH
          value: $(params.pyxis_cert_path)
        - name: PYXIS_KEY_PATH
          value: $(params.pyxis_key_path)
      script: |
        #! /usr/bin/env bash
        exit 0
        set -xe

        # Somehow, when not assigned to a var, this param has a trailing new line
        ASSOCIATION=$(params.association)
        echo "Attempting to reserve operator name for assocation $ASSOCIATION"

        reserve-operator-name \
          --association $ASSOCIATION \
          --operator-name "$(params.operator_name)" \
          --pyxis-url "$(params.pyxis_url)" \
          --source "certified-operators" \
          --verbose
