---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: set-quay-repo-visibility
spec:
  params:
    - name: pipeline_image
    - name: repository
      description: Fill container repository path (e.g. <namespace>/<repo-name>)
    - name: visibility
      description: public or private
    - name: oauth_secret_name
      description: The name of a secret containing the OAuth2 token
    - name: oauth_secret_key
      description: The name of the key in the secret containing the OAuth2 token
  steps:
    - name: change-visibility
      image: "$(params.pipeline_image)"
      env:
        - name: QUAY_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.oauth_secret_name)
              key: $(params.oauth_secret_key)
      script: |
        #! /usr/bin/env bash
        # DO NOT use `set -x` to avoid exposing the OAuth token
        set -e

        curl -X POST \
          -H "Authorization: Bearer $QUAY_OAUTH_TOKEN" \
          -H "Content-Type:application/json" \
          -d "{\"visibility\": \"$(params.visibility)\"}" \
          "https://quay.io/api/v1/repository/$(params.repository)/changevisibility"

        echo "Repository visibility set to '$(params.visibility)'."
