---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-env
spec:
  params:
    - name: env
      description: Environment. One of [dev, qa, stage, production]
    - name: access_type
      description: Pyxis access type. One of [internal, external]
  results:
    - name: pyxis_url
      description: Container API URL based for selected environment
    - name: target_branch
      description: Target branch for submitted PR in upstream repository
    - name: connect_url
      description: Connect SPA URL based on selected environment
    - name: iib_url
      description: IIB URL based on selected environment
  steps:
    - name: set-env
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        set -ex

        ENV="$(params.env)"
        ACCESS_TYPE="$(params.access_type)"

        if ! [[ "$ACCESS_TYPE" =~ ^(internal|external)$ ]]; then
            echo "Unknown access type."
            exit 1
        fi

        case $ENV in
            production)
                case $ACCESS_TYPE in
                    internal)
                    PYXIS_URL="https://pyxis.engineering.redhat.com"
                    ;;
                    external)
                    PYXIS_URL="https://catalog.redhat.com/api/containers/"
                    ;;
                esac
                TARGET_BRANCH="main"
                CONNECT_URL="https://connect.redhat.com"
                IIB_URL="https://iib.engineering.redhat.com"
            ;;
            stage)
                case $ACCESS_TYPE in
                    internal)
                    PYXIS_URL="https://pyxis.stage.engineering.redhat.com"
                    ;;
                    external)
                    PYXIS_URL="https://pyxis-isv-stage.api.redhat.com"
                    ;;
                esac
                TARGET_BRANCH="stage"
                CONNECT_URL="https://connect.stage.redhat.com"
                IIB_URL="https://iib.stage.engineering.redhat.com"
            ;;
            qa)
                case $ACCESS_TYPE in
                    internal)
                    PYXIS_URL="https://pyxis.qa.engineering.redhat.com"
                    ;;
                    external)
                    PYXIS_URL="https://pyxis-isv-qa.api.redhat.com"
                    ;;
                esac
                TARGET_BRANCH="qa"
                CONNECT_URL="https://connect.qa.redhat.com"
                IIB_URL="https://iib.stage.engineering.redhat.com"
            ;;
            dev)
                case $ACCESS_TYPE in
                    internal)
                    PYXIS_URL="https://pyxis.dev.engineering.redhat.com"
                    ;;
                    external)
                    PYXIS_URL="https://pyxis-isv-dev.api.redhat.com"
                    ;;
                esac
                TARGET_BRANCH="dev"
                CONNECT_URL="https://connect.dev.redhat.com"
                IIB_URL="https://iib.stage.engineering.redhat.com"
            ;;
            *)
                echo "Unknown environment."
                exit 1
                ;;
        esac

        echo -n $PYXIS_URL | tee $(results.pyxis_url.path)
        echo -n $TARGET_BRANCH | tee $(results.target_branch.path)
        echo -n $CONNECT_URL | tee $(results.connect_url.path)
        echo -n $IIB_URL | tee $(results.iib_url.path)
