---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: submission-validation
spec:
  params:
    - name: image_tag
    - name: git_username
    - name: git_pr_title
    - name: git_pr_url
    - name: pyxis_url
      default: https://catalog.redhat.com/api/containers
    - name: github_usernames
      description: List of accounts with permissions allowing operator submission
  results:
    - name: cert_project_id
    - name: operator_name
    - name: bundle_version
  workspaces:
    - name: source
  steps:
    - name: submission-validation
      workingDir: $(workspaces.source.path)
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      script: |
        #! /usr/bin/env bash
        set -xe

        # 1. Verify via regex if PR title follows convention
        # 2. Verify, that new version is added and no existing one modified
        # 3. Verify, if the user which created the PR is allowed to
        # submit the operator
        # 4. Verify that there is no other open PRs for this operator
        verify-submission \
          --pr-title "$(params.git_pr_title)" \
          --available-repositories redhat-openshift-ecosystem/operator-pipelines-test \
          --pr-url $(params.git_pr_url) \
          --git-username $(params.git_username) \
          --verbose \
          --contacts $(params.github_usernames)

        cat bundle_name | tee $(results.operator_name.path)
        cat bundle_version | tee $(results.bundle_version.path)
